GET http://localhost:8080/restart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTY0MDY0MzY3NX0.P9uPRbpZrb6nB1SuTFLaBVUhzrnGzE6Vt-bQJFvg0vc

###

POST  http://localhost:8080/test
Content-Type: application/json

{

}
###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Tim",
    "password": "tim"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Hans",
    "password": "123456",
    "email": "gpunkt@lacil.de"
}
###

GET http://localhost:8080/dashboarddata
Content-Type: application/json

{
    
}

###

GET http://localhost:8080/restart
