GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGltIiwiaWF0IjoxNjM1NDE4OTEyfQ.se5Mim3prS5EED3wVpBvMm1OpQWo0oukUCRMa9PWq3I

###

GET http://localhost:8080/test
Content-Type: application/json

{
    "username": "wad"
}
###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Tim",
    "password": "123456"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "fsadwef",
    "password": "123456",
    "email": "tlaadwefh@tlharken.de"
}