GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVG9iaSIsImlhdCI6MTYzNTU0MjIzM30.6EJUSV16c6l7XXtSY27TUJIEo4UX7KtsIZ8EH5F3SL8

###

GET http://localhost:8080/test
Content-Type: application/json

{
    "username": "wad"
}
###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Tobi",
    "password": "123456"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Tobi",
    "password": "123456",
    "email": "gpunkt@lachsgeil.de"
}
###

GET http://localhost:8080/dashboarddata
Content-Type: application/json

{
    
}